### PR TITLE
Set the service account for the automation worker

### PR DESCRIPTION
**Pull request by bdunne**
Requires: https://github.com/ManageIQ/manageiq-pods/pull/995

### CODE REVIEW

**Comment by agrare** [comment]
@bdunne I just cherry-picked your commit to save the extra merge commit

**Comment by bdunne** [comment]
Sorry, looks like specs failed.  I'm investigating

**Comment by agrare** [comment]
👍 no worries just let me know when you're happy with it and I'll pull it in again

**Comment by bdunne** [comment]
@agrare This should be good to go now.  The test passes locally.

**Pull request closed without merging**
